### ISSUE TITLE
Alert when user goes 'back' that their answers will be lost

### ISSUE THREAD

**Issue by knod** [codeforboston/docassemble-juvenilesealing#66] opened 2020-03-11 00:35 UTC
When they press back, I believe their answers on that previous screen are destroyed, as are the answers on their current screen.

**Comment by knod** [comment] 2020-03-11 00:35
Maybe not part of the MVP, but very painful.

**Comment by knod** [comment] 2020-03-11 00:36
Can offer them the option of a review screen at the end to fix things they want to change.

**Comment by niharikasingh** [comment] 2020-07-31 23:49
Duplicate of https://github.com/codeforboston/docassemble-juvenilesealing/issues/118

**Closed by niharikasingh** 2020-07-31 23:49 UTC
Labels: enhancement
